# Generated by Django 2.2 on 2021-08-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('AuthorName', models.IntegerField(max_length=20)),
            ],
        ),
    ]
